create extension if not exists pgcrypto;

create schema if not exists carga;
create schema if not exists bronze;
create schema if not exists consulta;

-- ============================================================
-- 1. ARCHIVO FÍSICO
-- Un archivo Usos(fecha) se registra UNA sola vez.
-- ============================================================
create table if not exists carga.archivo_etl (
    id uuid primary key default gen_random_uuid(),
    nombre_archivo text not null,
    tipo_archivo text not null
        check (tipo_archivo in ('RECAUDO_USOS', 'DIA_TIPO', 'PSO')),
    sha256_archivo char(64) not null unique,
    tamano_bytes bigint not null,
    fecha_modificacion_origen timestamptz,
    fecha_archivo date,
    ruta_origen text,
    estado text not null default 'REGISTRADO'
        check (estado in (
            'REGISTRADO','CARGANDO','CARGADO',
            'CARGADO_PARCIAL','DUPLICADO','ERROR','RECHAZADO'
        )),
    mensaje_error text,
    iniciado_en timestamptz not null default now(),
    finalizado_en timestamptz,
    creado_en timestamptz not null default now()
);

create index if not exists ix_archivo_etl_tipo
    on carga.archivo_etl(tipo_archivo);

create index if not exists ix_archivo_etl_estado
    on carga.archivo_etl(estado);

-- ============================================================
-- 2. DATASETS CONTENIDOS EN EL ARCHIVO
-- RECAUDO_USOS -> USOS + USOS_VALIDADOR
-- DIA_TIPO     -> DIA_TIPO
-- ============================================================
create table if not exists carga.dataset_etl (
    id uuid primary key default gen_random_uuid(),
    archivo_id uuid not null
        references carga.archivo_etl(id) on delete cascade,
    tipo_dataset text not null
        check (tipo_dataset in ('USOS','USOS_VALIDADOR','DIA_TIPO','PSO')),
    sha256_contenido char(64) not null,
    estado text not null default 'REGISTRADO'
        check (estado in (
            'REGISTRADO','CARGANDO','CARGADO',
            'DUPLICADO','ERROR','RECHAZADO'
        )),
    filas_leidas integer not null default 0,
    filas_cargadas integer not null default 0,
    filas_rechazadas integer not null default 0,
    fecha_min date,
    fecha_max date,
    mensaje_error text,
    iniciado_en timestamptz not null default now(),
    finalizado_en timestamptz,
    constraint uq_dataset_archivo_tipo
        unique (archivo_id, tipo_dataset)
);

create index if not exists ix_dataset_tipo_hash
    on carga.dataset_etl(tipo_dataset, sha256_contenido);

create index if not exists ix_dataset_estado
    on carga.dataset_etl(estado);

-- ============================================================
-- 3. ERRORES
-- ============================================================
create table if not exists carga.error_etl (
    id bigint generated by default as identity primary key,
    archivo_id uuid references carga.archivo_etl(id) on delete cascade,
    dataset_id uuid references carga.dataset_etl(id) on delete cascade,
    etapa text not null,
    fila_origen integer,
    campo text,
    valor text,
    codigo_error text,
    detalle text not null,
    creado_en timestamptz not null default now()
);

-- ============================================================
-- 4. BRONZE - USOS
-- ============================================================
create table if not exists bronze.usos (
    id bigint generated by default as identity primary key,
    dataset_id uuid not null
        references carga.dataset_etl(id),
    fila_origen integer not null,
    fecha date not null,
    estacion text not null,
    h1 numeric, h2 numeric, h3 numeric, h4 numeric, h5 numeric, h6 numeric,
    h7 numeric, h8 numeric, h9 numeric, h10 numeric, h11 numeric, h12 numeric,
    h13 numeric, h14 numeric, h15 numeric, h16 numeric, h17 numeric, h18 numeric,
    h19 numeric, h20 numeric, h21 numeric, h22 numeric, h23 numeric,
    cargado_en timestamptz not null default now(),
    constraint uq_bronze_usos_dataset_fila
        unique (dataset_id, fila_origen)
);

create index if not exists ix_bronze_usos_fecha
    on bronze.usos(fecha);

-- ============================================================
-- 5. BRONZE - USOS VALIDADOR
-- ============================================================
create table if not exists bronze.usos_validador (
    id bigint generated by default as identity primary key,
    dataset_id uuid not null
        references carga.dataset_etl(id),
    fila_origen integer not null,
    fecha date not null,
    estacion text,
    veh_id text,
    usos_validador numeric,
    cargado_en timestamptz not null default now(),
    constraint uq_bronze_uv_dataset_fila
        unique (dataset_id, fila_origen)
);

create index if not exists ix_bronze_uv_fecha
    on bronze.usos_validador(fecha);

create index if not exists ix_bronze_uv_veh_id
    on bronze.usos_validador(veh_id);

-- ============================================================
-- 6. BRONZE - DIA TIPO
-- ============================================================
create table if not exists bronze.dia_tipo (
    id bigint generated by default as identity primary key,
    dataset_id uuid not null
        references carga.dataset_etl(id),
    fila_origen integer not null,
    fecha date not null,
    dia_tipo_origen text not null,
    dia_tipo text not null,
    cargado_en timestamptz not null default now(),
    constraint uq_bronze_dt_dataset_fila
        unique (dataset_id, fila_origen)
);

create index if not exists ix_bronze_dia_tipo_fecha
    on bronze.dia_tipo(fecha);

-- ============================================================
-- 7. CATÁLOGO DE NORMALIZACIÓN DÍA TIPO
-- No inventa categorías nuevas; solo traduce códigos conocidos.
-- ============================================================
create table if not exists consulta.cat_dia_tipo (
    codigo_origen text primary key,
    codigo_normalizado text not null,
    activo boolean not null default true
);

-- Regla conocida del proceso actual.
insert into consulta.cat_dia_tipo(codigo_origen, codigo_normalizado)
values ('FEST', 'FES')
on conflict (codigo_origen) do nothing;

-- ============================================================
-- 8. DIA TIPO ACTUAL
-- La versión más reciente CARGADA gana por fecha.
-- ============================================================
create or replace view consulta.dim_dia_tipo_actual as
select distinct on (dt.fecha)
    dt.fecha,
    dt.dia_tipo,
    dt.dia_tipo_origen,
    d.id as dataset_id,
    a.id as archivo_id,
    a.nombre_archivo,
    dt.cargado_en
from bronze.dia_tipo dt
join carga.dataset_etl d on d.id = dt.dataset_id
join carga.archivo_etl a on a.id = d.archivo_id
where d.estado = 'CARGADO'
  and a.estado in ('CARGADO','CARGADO_PARCIAL')
order by dt.fecha, dt.cargado_en desc, dt.id desc;

-- ============================================================
-- 9. USOS VALIDADOR + DIA TIPO
-- ============================================================
create or replace view consulta.usos_validador_enriquecido as
select
    uv.id,
    uv.fecha,
    dt.dia_tipo,
    uv.estacion,
    uv.veh_id,
    uv.usos_validador,
    uv.dataset_id,
    d.archivo_id,
    a.nombre_archivo,
    uv.cargado_en
from bronze.usos_validador uv
join carga.dataset_etl d on d.id = uv.dataset_id
join carga.archivo_etl a on a.id = d.archivo_id
left join consulta.dim_dia_tipo_actual dt
    on dt.fecha = uv.fecha
where d.estado = 'CARGADO';

-- ============================================================
-- 10. RESUMEN DIARIO
-- ============================================================
create or replace view consulta.resumen_usos_validador_dia as
select
    fecha,
    dia_tipo,
    count(*) as registros,
    sum(coalesce(usos_validador,0)) as total_usos_dia
from consulta.usos_validador_enriquecido
group by fecha, dia_tipo;

-- ============================================================
-- 11. USOS EN FORMATO LARGO
-- ============================================================
create or replace view consulta.usos_hora as
select
    u.id as usos_id,
    u.fecha,
    u.estacion,
    v.hora,
    v.usos,
    u.dataset_id,
    d.archivo_id,
    a.nombre_archivo
from bronze.usos u
join carga.dataset_etl d on d.id = u.dataset_id
join carga.archivo_etl a on a.id = d.archivo_id
cross join lateral (
    values
        (1,u.h1),(2,u.h2),(3,u.h3),(4,u.h4),(5,u.h5),(6,u.h6),
        (7,u.h7),(8,u.h8),(9,u.h9),(10,u.h10),(11,u.h11),(12,u.h12),
        (13,u.h13),(14,u.h14),(15,u.h15),(16,u.h16),(17,u.h17),(18,u.h18),
        (19,u.h19),(20,u.h20),(21,u.h21),(22,u.h22),(23,u.h23)
) as v(hora, usos)
where d.estado = 'CARGADO';

-- ============================================================
-- 12. AUDITORÍA
-- ============================================================
create or replace view consulta.auditoria_archivos as
select
    a.id as archivo_id,
    a.nombre_archivo,
    a.tipo_archivo,
    a.sha256_archivo,
    a.fecha_archivo,
    a.estado as estado_archivo,
    d.id as dataset_id,
    d.tipo_dataset,
    d.sha256_contenido,
    d.estado as estado_dataset,
    d.filas_leidas,
    d.filas_cargadas,
    d.filas_rechazadas,
    d.fecha_min,
    d.fecha_max,
    a.iniciado_en,
    a.finalizado_en
from carga.archivo_etl a
left join carga.dataset_etl d
    on d.archivo_id = a.id;
